#! /bin/bash

if [ "$1" == "" ]
then
	echo 'No name provided'
	exit 1
fi

KEY=$1

LINE=$(docker ps | grep $KEY | head -1)
ID="$(cut -d' ' -f1 <<<$LINE)"
FULLIMGNAME="$(cut -d' ' -f2 <<<$LINE)"

if [ $ID ]
then
	echo "Running into $FULLIMGNAME"
	docker exec -it $ID /bin/bash
else
	echo "No image name containing $KEY"
	exit 2
fi
